# Generated by Django 3.2.4 on 2021-06-24 09:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoisk_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
